root_path: ./data/anisotropic_fixed_lon_file/2D
internal_family_file: G_shear_n50_circular_middle_refined_mesh_new_lon_file.h5
external_family_file: G_shear_n35_circular_middle_refined_mesh_new_lon_file.h5
splits:
  train_test_size: 0.8
  test_val_size: 0.87
random_seed: 1234