include_geometric_descriptor: True
include_F_loss: False
geometric_descriptor: pca
use_global_D: False
use_LPM: True
dimensions: 3
model:
  activation_function: tanh
  description: Uses LPM technique and includes pca geometric descriptor
  hidden_layers: 8
  hidden_units:  64
  input_size: 6 #13
  name: LG-PINN
  output_size: 2
optimizer:
  learning_rate: 0.001
  lr_scheduler: none
  lr_scheduler_gamma: 0.98
  name: Adam
random_seed: 42
training:
  batch_size: 264
  epochs: 5000
  loss_weights:
    bc: 1
    data: 1
    init: 1
    ode: 1
    pde: 1
  splits:
    num_boundary_points: 160 #80
    num_collocation_points: 1400 #700
    num_initial_points: 60 #30
    num_supervised_points: 14
  val_epochs: 10
  grad_clip_norm: 1.0
  val_method: max_mse_loss